### ISSUE TITLE
Doesn't work with Python 3.10

### ISSUE THREAD

**Issue by philn** [beeware/gbulb#53]
```
    self.loop.run_until_complete(asyncio.gather(*tasks))
  File "/var/home/phil/.local/lib/python3.10/site-packages/gbulb/glib_events.py", line 837, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.10/asyncio/streams.py", line 113, in start_unix_server
    return await loop.create_unix_server(factory, path, **kwds)
TypeError: _UnixSelectorEventLoop.create_unix_server() got an unexpected keyword argument 'loop'
```

**Comment by philn** [comment]
Ah sorry that's a bug in my code actually. Wasn't obvious from the traceback.
